name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Create Deploy Directory
        run: mkdir deploy

      - name: Copy Files to Deploy Directory
        run: rsync -av * deploy/

      - name: Navigate to Deploy Directory
        run: cd deploy

      - name: Initialize Git Repository
        run: |
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add Files
        run: git add .

      - name: Commit Changes
        run: git commit -m "Deploy Website to GitHub Pages"

      - name: Push to GitHub Pages
        run: git push --force --quiet "https://***@github.com/ShaneBonkowski/ShanesGames.git" HEAD:gh-pages
