name: Deploy Website to GitHub Pages

on:
  push:
    # When pushed to main branch, kick off this GitHub Action
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Remove Unnecessary Files From Build
        run: |
          rm -rf .git*  # Remove Git-related files and folders
          rm -rf .github  # Remove GitHub Actions files and folders
          rm -rf README*  # Remove README files
          rm -rf LICENSE*  # Remove license files
          rm -rf ./*/*.md  # Remove markdown files in subdirectories
          # Add more commands to remove other unnecessary files as needed

      - name: Create Deploy Directory
        run: mkdir deploy

      - name: Copy Files to Deploy Directory
        run: rsync -av * deploy/

      - name: Navigate to Deploy Directory
        run: cd deploy

      - name: Insert Google Analytics Tracking Code
        run: |
          # Get the Google Analytics tracking ID from GitHub secrets
          GA_TRACKING_ID=$GA_TRACKING_ID_SECRET

          # Find all HTML files in the deploy directory
          HTML_FILES=$(find . -type f -name "*.html")

          # Iterate over each HTML file
          for FILE in $HTML_FILES; do
            # Check if the file contains a <head> element
            if grep -q "<head>" "$FILE"; then
                # Insert the Google Analytics tracking code after the <head> element
                sed -i '/<head>/a\
                <!-- Google tag (gtag.js) -->\
                <script async src="https://www.googletagmanager.com/gtag/js?id='"$GA_TRACKING_ID"'"></script>\
                <script>\
                window.dataLayer = window.dataLayer || [];\
                function gtag(){dataLayer.push(arguments);}\
                gtag("js", new Date());\
                gtag("config", "'"$GA_TRACKING_ID"'");\
                </script>\
                ' "$FILE"
            else
                echo "Warning: $FILE does not contain a <head> element. Skipping."
            fi
          done
        env:
          GA_TRACKING_ID_SECRET: ${{secrets.GA_TRACKING_ID}}

      - name: Initialize Git Repository
        run: |
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"

      - name: Add Files
        run: git add .

      - name: Commit Changes
        run: git commit -m "Deploy Website to GitHub Pages"

      - name: Check if gh-pages branch exists
        run: git show-ref --verify --quiet refs/heads/gh-pages
        continue-on-error: true
        id: check_branch

      - name: Create gh-pages branch if it doesn't exist
        if: steps.check_branch.outcome != 'success'
        run: git checkout -b gh-pages

      # Use GitHub token to push to pages via committing to gh-pages branch
      - name: Push to GitHub Pages
        run: git push --force --quiet "https://${{secrets.GH_TOKEN}}@github.com/ShaneBonkowski/ShanesGames.git" HEAD:gh-pages
